"use client";
import { useState } from "react";
import { MapPin } from "lucide-react";
type Session = { time: string; endTime: string; title: string; speaker: string; org: string; location: string; type: "Plenary" | "Breakout" | "Workshop" | "Social" };
type Break = { time: string; label: string };
type Day = { day: string; date: string; sessions: (Session | Break)[] };
const days: Day[] = [{ day: "Day 1", date: "9 Mar", sessions: [{ time: "08:00", label: "Registration & Welcome Coffee" }, { time: "09:00", endTime: "10:30", title: "Opening Plenary: Pathways to Impact", speaker: "Dr. Helena Moreau", org: "OAK Foundation", location: "Main Hall A", type: "Plenary" }, { time: "10:30", label: "Coffee Break" }, { time: "10:50", endTime: "12:00", title: "Thematic Dialogue: Climate Justice & Grantmaking", speaker: "Samuel Okafor", org: "Africa Climate Alliance", location: "Conference Room B2", type: "Breakout" }, { time: "13:30", endTime: "14:30", title: "Partner Spotlight: Rights-Based Approaches", speaker: "Fatima Zahra Benali", org: "MENA Rights Group", location: "Main Hall A", type: "Plenary" }, { time: "18:00", endTime: "20:00", title: "Welcome Reception & Dinner", speaker: "", org: "", location: "Rooftop Terrace", type: "Social" }] }, { day: "Day 2", date: "10 Mar", sessions: [] }, { day: "Day 3", date: "11 Mar", sessions: [] }];
function isBreak(item: Session | Break): item is Break { return "label" in item; }
export default function Programme() { const [activeDay, setActiveDay] = useState(0); const current = days[activeDay]; return <div className="max-w-3xl"><h1 className="text-2xl font-bold text-slate-900">Programme</h1><p className="mb-6 mt-1 text-sm text-slate-500">OAK Partner Convening 2026</p><div className="mb-6 grid grid-cols-3 gap-3">{days.map((day, index) => <button key={day.day} onClick={() => setActiveDay(index)} className={`rounded-2xl px-4 py-3 text-left ${index === activeDay ? "bg-navy-900 text-white" : "bg-white text-slate-800 shadow-card"}`}><p className="text-xs font-medium">{["MON", "TUE", "WED"][index]}</p><p className="text-lg font-bold">{day.day}</p><p className="text-xs opacity-70">{day.date}</p></button>)}</div><div className="flex flex-col gap-3">{current.sessions.map((item, index) => isBreak(item) ? <div key={index} className="flex items-center gap-3 py-1"><span className="w-12 text-xs text-slate-400">{item.time}</span><div className="h-px flex-1 border-t border-dashed border-slate-200" /><span className="text-xs text-slate-400">{item.label}</span></div> : <article key={index} className="rounded-2xl bg-white p-4 shadow-card"><div className="flex gap-4"><span className="w-14 shrink-0 text-xs text-slate-400">{item.time}<br />– {item.endTime}</span><div className="flex-1"><h2 className="text-sm font-semibold text-slate-800">{item.title}</h2>{item.speaker && <p className="mt-1 text-xs text-slate-500">{item.speaker} · {item.org}</p>}<p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><MapPin size={11} />{item.location}</p></div><span className="text-xs text-slate-500">{item.type}</span></div></article>)}</div></div>; }
