"use client";

import Link from "next/link";
import { AlertTriangle, HelpCircle, QrCode, RotateCcw } from "lucide-react";
import AdminShell from "../../admin-shell";

export default function NotRecognisedPage() {
  return <AdminShell><section className="space-y-4"><header><p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-400">Event check-in</p><h1 className="mt-1 text-[18px] font-bold">Check-in result</h1></header><section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center gap-3 bg-gradient-to-r from-[#f43f46] to-[#ff5459] p-4 text-white"><AlertTriangle className="h-7 w-7" /><div><h2 className="text-sm font-bold">QR not recognised</h2><p className="text-[9px] text-rose-50">This code could not be matched to an attendee.</p></div></div><div className="space-y-3 p-4"><p className="text-[10px] font-semibold text-slate-700">Possible reasons:</p><div className="space-y-2 text-[9px] text-slate-500"><p className="flex items-start gap-2"><span className="text-rose-500">•</span> The attendee has not completed registration</p><p className="flex items-start gap-2"><span className="text-rose-500">•</span> The QR code is damaged or expired</p><p className="flex items-start gap-2"><span className="text-rose-500">•</span> This is not an OAK attendee pass</p></div></div></section><Link href="/admin/checkin" className="flex items-center justify-center gap-2 rounded-xl bg-[#142f55] py-3 text-[10px] font-semibold text-white"><RotateCcw className="h-3.5 w-3.5" /> Try again</Link><Link href="/register" className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white py-3 text-[10px] font-semibold text-slate-700"><HelpCircle className="h-3.5 w-3.5" /> Create attendee registration</Link><div className="flex items-center justify-center gap-1 text-[8px] text-slate-400"><QrCode className="h-3 w-3" /> Ask the attendee to show their digital pass</div></section></AdminShell>;
}
